AWSTemplateFormatVersion: 2010-09-09
Description: Temporary, on-demand EC2 instances.
Resources:

  DemoBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub demo-bucket-${AWS::AccountId}
      NotificationConfiguration:
        LambdaConfigurations: # Why?  This causes our S3 bucket to invoke our Lambda function, whenever a file is uploaded.
          - Function: !GetAtt DemoLambdaFunction.Arn
            Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: app_runner/input/
                  - Name: suffix
                    Value: .zip

  DemoLambdaExecutionRole: # Why?  During execution, every Lambda function MUST assume a role, which determines its permissions.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess # Why?  So we can launch EC2 instances.
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess # Why?  So our log messages appear on CloudWatch.
        - arn:aws:iam::aws:policy/IAMFullAccess # Why?  So we can launch EC2 instances with auto-generated, temporary AWSCLI access keys.

  DemoLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: ec2_run.handler
      Role: !GetAtt DemoLambdaExecutionRole.Arn
      Code: # Why?  The code below is a placeholder.  We will replace it later.  See deploy.py.
        ZipFile: |
          def handler(event, context):
              pass
      Runtime: python3.6

  DemoLambdaInvokePermission: # Why?  Here, Lambda is basically saying, 'S3, I give you permission to invoke me.'
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DemoLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::demo-bucket-${AWS::AccountId}

  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: demo-security-group
      GroupDescription: Enables inbound SSH traffic.
      SecurityGroupIngress: # Why?  '0.0.0.0/0' is a wildcard.  So, we saying that ANY IP address can SSH into our EC2.
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  DemoEC2Role: # Why?  Determines what our EC2 instance is allowed to do via AWSCLI.  In this case, we permit S3 access.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  DemoInstanceProfile: # Why?  So our EC2 is launched with auto-generated, temporary AWSCLI access keys.
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref DemoEC2Role
      InstanceProfileName: demo-instance-profile

Outputs:
  DemoBucketArn:
    Value: !GetAtt DemoBucket.Arn
  DemoLambdaFunctionArn:
    Value: !GetAtt DemoLambdaFunction.Arn